# Generated by Django 4.1.2 on 2022-10-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civil_Status',
            fields=[
                ('nationality_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male - ذكر'), ('Female', 'Female - أنثى')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('nationality_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.civil_status')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Examination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Biopsy', 'Biopsy'), ('Colonoscopy', 'Colonoscopy'), ('CT scan', 'CT scan'), ('CT scans and radiation exposure in children and young people', 'CT scans and radiation exposure in children and young people'), ('Electrocardiogram (ECG)', 'Electrocardiogram (ECG)'), ('Electroencephalogram (EEG)', 'Electroencephalogram (EEG)'), ('Gastroscopy', 'Gastroscopy'), ('Eye tests', 'Eye tests'), ('Hearing test', 'Hearing test'), ('MRI scan', 'MRI scan'), ('PET scan', 'PET scan'), ('Ultrasound', 'Ultrasound'), ('X-rays', 'X-rays')], max_length=200)),
                ('result', models.CharField(max_length=2000)),
                ('note', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient')),
                ('stuff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stuff')),
            ],
        ),
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Son', 'Son'), ('Daughter', 'Dauther'), ('Brother', 'Father'), ('Sister', 'Sister'), ('Uncle', 'Uncle'), ('aunt', 'aunt'), ('Grandfather', 'Grandfather'), ('grandmother', 'grandmother'), ('Step Father', 'Step Father'), ('Step Mother', 'Step Mother')], max_length=200)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient')),
            ],
        ),
    ]
