# Generated by Django 4.1.2 on 2022-10-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.UUIDField(default=10930582108, editable=False, primary_key=True, serialize=False),
        ),
    ]
