# Generated by Django 4.1.2 on 2022-10-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=48985590192, editable=False, primary_key=True, serialize=False),
        ),
    ]
