# Generated by Django 4.1.2 on 2022-10-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_stuff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='username',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=65673613828, editable=False, primary_key=True, serialize=False),
        ),
    ]
