# Generated by Django 4.1.2 on 2022-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_stuff_username_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=19891933171, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='password',
            field=models.CharField(default='3v4GoaRUx_GNVa8N', max_length=100),
        ),
    ]
