# Generated by Django 4.1.2 on 2022-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stuff_id_alter_stuff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=71200229882, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='password',
            field=models.UUIDField(default='<function uuid4 at 0x00000179149C6710>'),
        ),
    ]
