# Generated by Django 4.1.2 on 2022-10-23 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stuff_id_alter_stuff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=89622095987, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='password',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
