# Generated by Django 4.1.2 on 2022-10-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_stuff_id_alter_stuff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=14482240227, editable=False, primary_key=True, serialize=False),
        ),
    ]
