# Generated by Django 4.1.2 on 2022-10-23 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_stuff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='username',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.IntegerField(default=31441517128, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='password',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=36723848720, editable=False, primary_key=True, serialize=False),
        ),
    ]
