# Generated by Django 4.1.2 on 2022-10-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_hospital_hospital_id_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\mbaji\\Django\\Seha\\media'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=70959293859, editable=False, primary_key=True, serialize=False),
        ),
    ]
