# Generated by Django 4.1.2 on 2022-10-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_hospital_logo_alter_stuff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=69407927890, editable=False, primary_key=True, serialize=False),
        ),
    ]
