# Generated by Django 4.1.2 on 2022-10-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_hospital_active_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=63494064287, editable=False, primary_key=True, serialize=False),
        ),
    ]
