# Generated by Django 4.1.2 on 2022-11-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_hospital_active_alter_stuff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nationality_id',
        ),
        migrations.RemoveField(
            model_name='kin',
            name='patient',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=85801218254, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Medical_Examination',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
