# Generated by Django 4.1.2 on 2022-11-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_patient_nationality_id_remove_kin_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=16571593386, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('civil_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.civil_status')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Examination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Biopsy', 'Biopsy'), ('Colonoscopy', 'Colonoscopy'), ('CT scan', 'CT scan'), ('CT scans and radiation exposure in children and young people', 'CT scans and radiation exposure in children and young people'), ('Electrocardiogram (ECG)', 'Electrocardiogram (ECG)'), ('Electroencephalogram (EEG)', 'Electroencephalogram (EEG)'), ('Gastroscopy', 'Gastroscopy'), ('Eye tests', 'Eye tests'), ('Hearing test', 'Hearing test'), ('MRI scan', 'MRI scan'), ('PET scan', 'PET scan'), ('Ultrasound', 'Ultrasound'), ('X-rays', 'X-rays')], max_length=200)),
                ('result', models.CharField(max_length=2000)),
                ('note', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient')),
                ('stuff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stuff')),
            ],
        ),
        migrations.AddField(
            model_name='kin',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient'),
        ),
    ]
