# Generated by Django 4.1.2 on 2022-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_patient_date_alter_stuff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='date',
            field=models.DateField(blank=True, default='2022-11-04'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=22655122390, editable=False, primary_key=True, serialize=False),
        ),
    ]
