# Generated by Django 4.1.2 on 2022-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_hospital_date_alter_patient_date_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=10162852585, editable=False, primary_key=True, serialize=False),
        ),
    ]
