# Generated by Django 4.1.2 on 2022-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_hospital_date_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=17502386317, editable=False, primary_key=True, serialize=False),
        ),
    ]
