# Generated by Django 4.1.2 on 2022-11-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_medical_examination_result_alter_stuff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_examination',
            name='stuff',
        ),
        migrations.AlterField(
            model_name='medical_examination',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=31292222871, editable=False, primary_key=True, serialize=False),
        ),
    ]
