# Generated by Django 4.1.2 on 2022-11-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_medical_examination_stuff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_examination',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=69619056994, editable=False, primary_key=True, serialize=False),
        ),
    ]
