# Generated by Django 4.1.2 on 2022-11-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_medical_examination_note_alter_stuff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_examination',
            old_name='note',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='medical_examination',
            old_name='file',
            new_name='result',
        ),
        migrations.AlterField(
            model_name='medical_examination',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=42977362152, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Basic_Health_State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Heart Rate', 'Heart Rate'), ('Oxygen Saturation', 'Oxygen Saturation'), ('Body Temperature', 'Body Temperature'), ('Glucose Level', 'Glucose Level')], max_length=200)),
                ('result', models.IntegerField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient')),
            ],
        ),
    ]
