# Generated by Django 4.1.2 on 2022-11-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_basic_health_state_date_alter_stuff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_health_state',
            old_name='oxygen_saturaion',
            new_name='oxygen_saturation',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=45428011106, editable=False, primary_key=True, serialize=False),
        ),
    ]
