# Generated by Django 4.1.2 on 2022-11-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_oxygen_saturaion_basic_health_state_oxygen_saturation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=81918630407, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('Heart Disease', 'Heart Disease'), ('Skin Care', 'Skin Care'), ('Diabetes Disease', 'Diabetes Disease')], max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient')),
            ],
        ),
    ]
