# Generated by Django 4.1.2 on 2022-11-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_stuff_id_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=87709462759, editable=False, primary_key=True, serialize=False),
        ),
    ]
