# Generated by Django 4.1.2 on 2022-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_stuff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=33859371889, editable=False, primary_key=True, serialize=False),
        ),
    ]
