# Generated by Django 4.1.2 on 2022-11-11 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_prescription_start_date_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=50688827565, editable=False, primary_key=True, serialize=False),
        ),
    ]
