# Generated by Django 4.1.2 on 2022-11-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_prescription_start_date_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(default=18138489773, editable=False, primary_key=True, serialize=False),
        ),
    ]
