# Generated by Django 4.1.2 on 2022-12-04 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_basic_health_state_patient_kin_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalprofile",
            name="date_joined",
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 4)),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="date_joined",
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 4)),
        ),
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=36209923589, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
