# Generated by Django 4.1.2 on 2022-12-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_hospitalprofile_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalprofile",
            name="date_joined",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="date_joined",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=55799794277, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
