# Generated by Django 4.1.2 on 2022-12-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_hospitalprofile_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=51676778039, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
