# Generated by Django 4.1.2 on 2022-12-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_hospitalprofile_is_deleted_patientprofile_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=46171445824, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
