# Generated by Django 4.1.2 on 2022-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_remove_user_first_name_remove_user_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="civil_status",
        ),
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=45399985571, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
