# Generated by Django 4.1.2 on 2022-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_remove_user_civil_status_alter_stuff_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=61023393062, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
