# Generated by Django 4.1.2 on 2022-12-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_remove_user_is_superuser_alter_stuff_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="photo",
            field=models.ImageField(
                blank=True, default="avatar.jpg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=26523765430, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Patient_Disease",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "disease",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.disease",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.patient",
                    ),
                ),
            ],
        ),
    ]
