# Generated by Django 4.1.2 on 2023-01-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_disease_alter_patientprofile_photo_alter_stuff_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=69379860566, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Hospital_Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "Hospital",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospital_for_patient",
                        to="api.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_in_hospital",
                        to="api.patient",
                    ),
                ),
            ],
        ),
    ]
