# Generated by Django 4.1.2 on 2023-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_alter_stuff_id_hospital_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="civil_status",
            name="photo",
            field=models.ImageField(
                blank=True, default="avatar.jpg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="stuff",
            name="id",
            field=models.IntegerField(
                default=29487758112, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
