# Generated by Django 4.1.2 on 2023-01-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_civil_status_photo_alter_stuff_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stuff",
        ),
    ]
