# Generated by Django 4.1.2 on 2023-01-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_rename_hospital_hospital_patient_hospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.hospital"
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.patient"
            ),
        ),
    ]
